- hosts: andy
  tasks:
    - name: install packages
      apt:
        name:
          - git
          - vim
          - sshfs
          - gnome-tweak-tool
          - stow
        state: present
      become: yes
