- hosts: andy
  become: yes
  tasks:

    - name: install packages
      apt:
        name:
          - git
          - vim
          - stow
          - sshfs
          - openscad
          - slic3r-prusa
          - flatpak
          - gnome-tweak-tool
          - geary
          - curl
          - apt-transport-https
          - ca-certificates
          - gnupg2
          - software-properties-common

    - name: remove packages
      apt:
        name:
          - evolution
          - gnome-music
        state: absent

    - name: add flathub
      flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: install flatpaks
      flatpak:
        name: "{{ item }}"
      loop:
        - org.telegram.desktop
        - com.bitwarden.desktop
        - org.zotero.Zotero
        - org.gnome.Games
        - com.spotify.Client
        - org.gnome.FeedReader

    # docker install
    - name: install the docker apt key
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        id: 0EBFCD88
    - name: install the docker apt repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
        update_cache: true

    - name: install docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: add alan
      user:
        name: nalanj
        comment: Alan Johnson
        groups: [sudo, docker]
