- hosts: andy
  become: yes
  tasks:
    - name: add alan
      user:
        name: nalanj
        comment: Alan Johnson
      register: nalanj

- hosts: andy
  become: yes
  roles:
    - role: autofs
      vars:
        nalanj: "{{ nalanj }}"
    - workstation-packages

