- hosts: andy
  become: yes
  handlers:
    - name: restart autofs
      service:
        name: autofs
        state: restarted

  tasks:
    - name: install packages
      dnf:
        name:
          - git
          - vim
          - stow
          - sshfs
          - autofs
          - openscad
          - flatpak
          - gnome-tweak-tool
          - geary
          - curl
          - gnupg2
          - libselinux-python

    - name: add flathub
      flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
    - name: install flatpaks
      flatpak:
        name: "{{ item }}"
      loop:
        - org.telegram.desktop
        - com.bitwarden.desktop
        - org.zotero.Zotero
        - org.gnome.Games
        - com.spotify.Client
        - org.gnome.FeedReader

    # docker install
#    - name: install the docker apt key
#      apt_key:
#        url: https://download.docker.com/linux/debian/gpg
#        id: 0EBFCD88
#    - name: install the docker apt repo
#      apt_repository:
#        repo: deb [arch=amd64] https://download.docker.com/linux/debian stretch stable
#        update_cache: true
#
#    - name: install docker
#      apt:
#        name:
#          - docker-ce
#          - docker-ce-cli
#          - containerd.io
#
#    - name: download micro
#      unarchive:
#        src: https://github.com/zyedidia/micro/releases/download/v1.4.1/micro-1.4.1-linux64.tar.gz
#        dest: /opt
#        remote_src: yes
#        creates: /opt/micro-1.4.1/micro
#    - name: copy micro
#      file:
#        src: /opt/micro-1.4.1/micro
#        dest: /usr/local/bin/micro
#        state: link
#
    - name: add alan
      user:
        name: nalanj
        comment: Alan Johnson
      register: nalanj

    - name: make autofs config dir
      file:
        name: /etc/auto.master.d/
        state: directory
      notify: restart autofs
    - name: create sshfs config
      copy:
        dest: /etc/auto.master.d/sshfs.autofs
        content: |
           /run/media/nalanj/sshfs /etc/auto.sshfs        uid={{ nalanj.uid }},gid={{ nalanj.uid }},--timeout=30,--ghost
      notify: restart autofs
    - name: create sshfs script
      copy:
        dest: /etc/auto.sshfs
        content: |
          smalls -fstype=fuse,rw,nodev,noatime,allow_other,max_read=65536 \:sshfs\#nalanj@smalls.616c616e.com\:/home/nalanj/share
      notify: restart autofs
