#!/bin/bash
set -ex

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# Symlink home
stow -d $DIR/ -t ~ home

sudo dnf install vim gnome-tweaks libselinux-python speedcrunch isync msmtp \
  mutt w3m stow ykpers

flatpak install -y flathub org.telegram.desktop com.bitwarden.desktop \
  org.zotero.Zotero

# copy u2f rules
sudo cp $DIR/etc/70-u2f.rules /etc/udev/rules.d/70-u2f.rules
sudo udevadm control --reload
sudo udevadm trigger

# Symlink vim config
vim +'PlugInstall --sync' +qa

# Link fonts
if [ ! -e ~/Downloads/plex.zip ]
then
  curl -L -o ~/Downloads/plex.zip https://github.com/IBM/plex/releases/download/v1.2.2/OpenType.zip
  unzip ~/Downloads/plex.zip -d ~/Downloads
  mkdir -p ~/.fonts/
  cp ~/Downloads/OpenType/IBM-Plex-Mono/*.otf ~/.fonts/
fi
fc-cache -f

# Install doctl
go get -u github.com/digitalocean/doctl/cmd/doctl
