- hosts: andy
  become: yes
  tasks:
    - name: add alan
      user:
        name: nalanj
        comment: Alan Johnson
      register: nalanj

- hosts: andy
  become: yes
  roles:
    - role: autofs
      vars:
        nalanj: "{{ nalanj }}"
    - workstation-packages

- hosts: andy
  become: yes
  tasks:
    - name: set spotify to hidpi
      copy:
        dest: /var/lib/flatpak/exports/share/applications/com.spotify.Client.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Name=Spotify
          GenericName=Music Player
          Icon=com.spotify.Client
          Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=spotify --file-forwarding com.spotify.Client --force-device-scale-factor=2.5 @@u %U @@
          Terminal=false
          MimeType=x-scheme-handler/spotify;
          Categories=Audio;Music;Player;AudioVideo;
          StartupWMClass=spotify
          StartupWMClass=Spotify
          X-Flatpak-Tags=proprietary;
          X-Flatpak=com.spotify.Client

