- name: install packages
  dnf:
    name:
      - git
      - vim
      - stow
      - sshfs
      - autofs
      - openscad
      - flatpak
      - gnome-tweak-tool
      - geary
      - curl
      - gnupg2
      - libselinux-python
      - gnome-keyring
      - seahorse
      - adobe-source-code-pro-fonts
      - tmux
      - gnome-music
      - fish

- name: add flathub
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
- name: install flatpaks
  flatpak:
    name: "{{ item }}"
  loop:
    - org.telegram.desktop
    - com.bitwarden.desktop
    - org.zotero.Zotero
    - org.gnome.Games
    - com.spotify.Client
    - org.gnome.FeedReader
    - org.gnome.Fractal
    - org.gnome.Genius

- name: install go
  unarchive:
    src: https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/go
