- name: set up rpmfusion
  dnf:
    name:
      - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-30.noarch.rpm
      - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-30.noarch.rpm
    state: present

- name: install packages
  dnf:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop:
    - state: present
      name:
        - git
        - vim
        - gvim
        - stow
        - sshfs
        - autofs
        - openscad
        - flatpak
        - gnome-tweak-tool
        - geary
        - curl
        - gnupg2
        - libselinux-python
        - gnome-keyring
        - seahorse
        - adobe-source-code-pro-fonts
        - tmux
        - gnome-music
        - fish
        - task
        - speedcrunch
        - hub
        - compat-ffmpeg28
        - ffmpeg-libs

- name: add flathub
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
- name: install flatpaks
  flatpak:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop:
    - { name: org.telegram.desktop, state: present }
    - { name: com.bitwarden.desktop, state: present }
    - { name: org.gnome.Games, state: present }
    - { name: com.spotify.Client, state: present }

- name: install go
  unarchive:
    src: https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes
    creates: /usr/local/go
