---
- name: make autofs config dir
  file:
    name: /etc/auto.master.d/
    state: directory
  notify: restart autofs

- name: create sshfs config
  copy:
    dest: /etc/auto.master.d/sshfs.autofs
    content: |
       /media/sshfs /etc/auto.sshfs        uid={{ nalanj.uid }},gid={{ nalanj.uid }},--timeout=30,--ghost
  notify: restart autofs
- name: create sshfs script
  copy:
    dest: /etc/auto.sshfs
    content: |
      smalls -fstype=fuse,rw,nodev,noatime,allow_other,max_read=65536 \:sshfs\#nalanj@smalls.616c616e.com\:/home/nalanj/share
  notify: restart autofs
