- name: install packages
  dnf:
    name:
      - git
      - vim
      - stow
      - sshfs
      - autofs
      - openscad
      - flatpak
      - gnome-tweak-tool
      - geary
      - curl
      - gnupg2
      - libselinux-python
      - gnome-keyring
      - seahorse

- name: add flathub
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
- name: install flatpaks
  flatpak:
    name: "{{ item }}"
  loop:
    - org.telegram.desktop
    - com.bitwarden.desktop
    - org.zotero.Zotero
    - org.gnome.Games
    - com.spotify.Client
    - org.gnome.FeedReader

